








apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 3.71.0
    helm.sh/chart: sensor-71.0.0
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
  name: collector-tls
  namespace: stackrox
type: Opaque
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXqgAwIBAgIUTWZDzGteHfypvw//ETMLoA6JMNkwCgYIKoZIzj0EAwIw
    SDEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYD
    VQQFExQxNzAzMDA3Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwMTEzMDBaFw0yNzA4
    MTAwMTEzMDBaMEgxJzAlBgNVBAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhv
    cml0eTEdMBsGA1UEBRMUMTcwMzAwNzM3NTgxODkxNjQ2MDQwWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAAQ5/RRzozwS+RazzqD9oVxUW7/72HKJlCVU+S787oxPoBea
    XrWyvaZwFyLvzCjr+LTJhEMFtSJmPbPMOM1KHgHAo0IwQDAOBgNVHQ8BAf8EBAMC
    AQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUWzswzWircLRrXDkvRq3df3xu
    Kt8wCgYIKoZIzj0EAwIDRwAwRAIgHXzkjgbccM8aX4uldyEMjqJyTT54ofAzaTOv
    Sr/0aJgCIGxrmaK7QQ1N5Tz3tHH5UmseVhHbMm4HSSxR10fcAMWs
    -----END CERTIFICATE-----
    
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICbzCCAhagAwIBAgIIASane+WYtrMwCgYIKoZIzj0EAwIwSDEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYDVQQFExQxNzAzMDA3
    Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwNDQwMDBaFw0yMzA4MTEwNTQwMDBaMHox
    GjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNFMUAwPgYDVQQDDDdDT0xMRUNUT1Jf
    U0VSVklDRTogZmQzZjM2MWQtOWYxYi00ZTQyLTg5YWYtYWU3ODQyYWZiYmUwMRow
    GAYDVQQFExE4MjkzNzc5MzcyNzczOTU3MTBZMBMGByqGSM49AgEGCCqGSM49AwEH
    A0IABG37VEGUP7FYFtdg2DpMWx+FSDPdeTV6oQj3IGpwxm10Ho/aH293lKR223+i
    gOPJDX/+l25CqYxZrBjC1Z93JCajgbcwgbQwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
    BBTDKl2gV4HvCjqplb4BD5Z48awHqDAfBgNVHSMEGDAWgBRbOzDNaKtwtGtcOS9G
    rd1/fG4q3zA1BgNVHREELjAsghJjb2xsZWN0b3Iuc3RhY2tyb3iCFmNvbGxlY3Rv
    ci5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDRwAwRAIgQSm7fKB45m/X4pAeT3Xn
    rQj7hV+Z3AchnXcUWAhXlrQCICRYoth/VGJQX/c2Pa9IIa2o4XAUq8buah9mtQ9H
    wYlK
    -----END CERTIFICATE-----
    
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIGMBUyP1ihCpQgKKVYdmpQHvPwnqD7m3k5Z9ZzV/PImDoAoGCCqGSM49
    AwEHoUQDQgAEbftUQZQ/sVgW12DYOkxbH4VIM915NXqhCPcganDGbXQej9ofb3eU
    pHbbf6KA48kNf/6XbkKpjFmsGMLVn3ckJg==
    -----END EC PRIVATE KEY-----
    
