























  
  
    
      
        






  
  
    
      
      
        
        
        





  
  
    
  


      
    
  

  
  
    
      
      
        
        
        





  
  
    
  


      
    
  


        
          
        
      
    
  

  
  
    
      
        






  
  
    
      
        






  
  
    
      
      
        
        
        





  
  
    
  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    
  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    





  
  
    
  


  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    





  
  
    
  


  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    
  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    
  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    





  
  
    
  


  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    





  
  
    
  


  


  


      
    
  


        
          
        
      
    
  

  
  

  
  
    
      
      
        
        
        





  
  
    
  


      
    
  

  
  

  
  

  
  
    
      
      
        
        
        





  
  
    
  


      
    
  

  
  
    
      
      
        
        
        





  
  
    
  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    
  


  


      
    
  

  
  

  
  

  
  
    
      
      
    
  

  
  

  
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    
  


  


      
    
  


        
      
    
  

  
  
    
      
        






  
  
    
      
      
        
        
        





  
  
    
  


      
    
  

  
  
    
      
      
        
        
        





  
  
    
  


      
    
  


        
          
        
      
    
  

  
  
    
      
      
        
        
        





  
  
    
  


      
    
  

  
  
    
      
        






  
  

  
  
    
      
        






  
  
    
      
      
        
        
        





  
  
    





  
  
    
  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    
  


  


      
    
  


        
          
        
      
    
  

  
  
    
      
        






  
  
    
      
      
        
        
        





  
  
    





  
  
    





  
  
    
  


  


  


      
    
  

  
  
    
      
      
        
        
        





  
  
    





  
  
    





  
  
    
  


  


  


      
    
  


        
          
        
      
    
  

  
  


        
      
    
  












  















  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  




















  











  
  
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  

  
  
  
    
    
    
    
    
    
    
    
    
  

  
  
  
    
    
    
    
    
    
    
    
    
  

  
  
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  

  
  
  
    
    
    
    
    
    
    
    
    
  

  
  
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
  

  
  
  
    
    
    
    
    
    
    
    
    
  














  
    
    
    
      






  
  



  
    
    
    
      
      
    
  
    
    
    
      
        
        
      
      
    
  
    
    
    
      






  
  



  
    
    
    
      
        
        
      
      
    
  
    
    
    
      
        
        
      
      
    
  


    
  


    
  
    
    
    
      






  
  



  
    
    
    
      
        
        
      
      
    
  


    
  
    
    
    
      






  
  



  
    
    
    
      
        
        
      
      
    
  
    
    
    
      
      
    
  
    
    
    
      
        
        
      
      
    
  
    
    
    
      






  
  



  
    
    
    
      
        
        
      
      
    
  
    
    
    
      
        
        
      
      
    
  


    
  


    
  
    
    
    
      






  
  



  
    
    
    
      
      
    
  
    
    
    
      
      
    
  


    
  
    
    
    
      






  
  



  
    
    
    
      
      
    
  
    
    
    
      
      
    
  


    
  
    
    
    
      






  
  



  
    
    
    
      
      
    
  
    
    
    
      
      
    
  


    
  
    
    
    
      






  
  




    
  
    
    
    
      






  
  



  
    
    
    
      
      
    
  
    
    
    
      
        
        
      
      
    
  
    
    
    
      






  
  



  
    
    
    
      
        
        
      
      
    
  
    
    
    
      
        
        
      
      
    
  


    
  


    
  


























  
    
    
      
    
  
    
    
      
    
  
    
    
      
    
  













  
  



  
    
    




    
  
  




  


  













  
    
    
      
    
  
    
    
      
    
  
    
    
      
    
  













  
  



  
  




  


  

















































  
    
  






  


























apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-upgrader
  namespace: stackrox
  labels:
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 3.71.0
    helm.sh/chart: sensor-71.0.0
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
imagePullSecrets:
- name: "secured-cluster-services-main"
- name: "stackrox"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:upgrade-sensors
  labels:
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 3.71.0
    helm.sh/chart: sensor-71.0.0
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
subjects:
- kind: ServiceAccount
  name: sensor-upgrader
  namespace: stackrox
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
