










apiVersion: v1
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
  labels:
    app.kubernetes.io/component: admission-control
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 3.71.0
    helm.sh/chart: sensor-71.0.0
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXqgAwIBAgIUTWZDzGteHfypvw//ETMLoA6JMNkwCgYIKoZIzj0EAwIw
    SDEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYD
    VQQFExQxNzAzMDA3Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwMTEzMDBaFw0yNzA4
    MTAwMTEzMDBaMEgxJzAlBgNVBAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhv
    cml0eTEdMBsGA1UEBRMUMTcwMzAwNzM3NTgxODkxNjQ2MDQwWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAAQ5/RRzozwS+RazzqD9oVxUW7/72HKJlCVU+S787oxPoBea
    XrWyvaZwFyLvzCjr+LTJhEMFtSJmPbPMOM1KHgHAo0IwQDAOBgNVHQ8BAf8EBAMC
    AQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUWzswzWircLRrXDkvRq3df3xu
    Kt8wCgYIKoZIzj0EAwIDRwAwRAIgHXzkjgbccM8aX4uldyEMjqJyTT54ofAzaTOv
    Sr/0aJgCIGxrmaK7QQ1N5Tz3tHH5UmseVhHbMm4HSSxR10fcAMWs
    -----END CERTIFICATE-----
    
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICkzCCAjmgAwIBAgIIF3mGteYMDD8wCgYIKoZIzj0EAwIwSDEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYDVQQFExQxNzAzMDA3
    Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwMTIxMDBaFw0yMzA4MTEwMjIxMDBaMIGM
    MSIwIAYDVQQLDBlBRE1JU1NJT05fQ09OVFJPTF9TRVJWSUNFMUgwRgYDVQQDDD9B
    RE1JU1NJT05fQ09OVFJPTF9TRVJWSUNFOiBjNGM4YjljOS00ZGU5LTRhYjctYTk2
    Ny1iZTBlZjkwN2ZlNGMxHDAaBgNVBAUTEzE2OTE1MzEyNTA4NjEwODM3MTEwWTAT
    BgcqhkjOPQIBBggqhkjOPQMBBwNCAAT/waKaACHV5t23Cfh4utemf/YiMo+ldpMv
    HkIQfB3mZleAFCN1YT2LfWfFDIAB+y5YWQC9+lBS732v5zPCKVR8o4HHMIHEMA4G
    A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYD
    VR0TAQH/BAIwADAdBgNVHQ4EFgQUIuGudrW1lNT4DZjdBEjbcqXVHRswHwYDVR0j
    BBgwFoAUWzswzWircLRrXDkvRq3df3xuKt8wRQYDVR0RBD4wPIIaYWRtaXNzaW9u
    LWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94LnN2
    YzAKBggqhkjOPQQDAgNIADBFAiAavtcIX0axU+AkyD2A2VsGw3wZITit99y5Frxg
    cbY3+AIhAOl6e5odoEdbEARzPDcWxPRAgHSlxLiiV8UXO/AouD5+
    -----END CERTIFICATE-----
    
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEILfZ53eHsIlvbBwmJaZeWzMAMGLU10xNilqoaPNO97WcoAoGCCqGSM49
    AwEHoUQDQgAE/8GimgAh1ebdtwn4eLrXpn/2IjKPpXaTLx5CEHwd5mZXgBQjdWE9
    i31nxQyAAfsuWFkAvfpQUu99r+czwilUfA==
    -----END EC PRIVATE KEY-----
    
