








apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 3.71.0
    helm.sh/chart: sensor-71.0.0
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
  name: collector-tls
  namespace: stackrox
type: Opaque
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXqgAwIBAgIUTWZDzGteHfypvw//ETMLoA6JMNkwCgYIKoZIzj0EAwIw
    SDEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYD
    VQQFExQxNzAzMDA3Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwMTEzMDBaFw0yNzA4
    MTAwMTEzMDBaMEgxJzAlBgNVBAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhv
    cml0eTEdMBsGA1UEBRMUMTcwMzAwNzM3NTgxODkxNjQ2MDQwWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAAQ5/RRzozwS+RazzqD9oVxUW7/72HKJlCVU+S787oxPoBea
    XrWyvaZwFyLvzCjr+LTJhEMFtSJmPbPMOM1KHgHAo0IwQDAOBgNVHQ8BAf8EBAMC
    AQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUWzswzWircLRrXDkvRq3df3xu
    Kt8wCgYIKoZIzj0EAwIDRwAwRAIgHXzkjgbccM8aX4uldyEMjqJyTT54ofAzaTOv
    Sr/0aJgCIGxrmaK7QQ1N5Tz3tHH5UmseVhHbMm4HSSxR10fcAMWs
    -----END CERTIFICATE-----
    
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICczCCAhigAwIBAgIIaNtXFwjjRS4wCgYIKoZIzj0EAwIwSDEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYDVQQFExQxNzAzMDA3
    Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwMTIxMDBaFw0yMzA4MTEwMjIxMDBaMHwx
    GjAYBgNVBAsMEUNPTExFQ1RPUl9TRVJWSUNFMUAwPgYDVQQDDDdDT0xMRUNUT1Jf
    U0VSVklDRTogYzRjOGI5YzktNGRlOS00YWI3LWE5NjctYmUwZWY5MDdmZTRjMRww
    GgYDVQQFExM3NTU1NzI4NTU2Mjg5MTE1NDM4MFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAEO/V6vB0tSwKL9EH0w5wUFNOs+76zlOpe9rMk1imc2dTACQRr/5Pop5YM
    YoHg4Mn2wp9BYk/ZAyUy5jpkSiJaRKOBtzCBtDAOBgNVHQ8BAf8EBAMCBaAwHQYD
    VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
    BBYEFCULmJURRhrSji0DESojYXW/jMT4MB8GA1UdIwQYMBaAFFs7MM1oq3C0a1w5
    L0at3X98birfMDUGA1UdEQQuMCyCEmNvbGxlY3Rvci5zdGFja3JveIIWY29sbGVj
    dG9yLnN0YWNrcm94LnN2YzAKBggqhkjOPQQDAgNJADBGAiEA1YfmXHwSBA7szRQY
    YHSqytP09WVzNlCAKDqu+I9i0RwCIQCEslI/zc+BX3YMpxrEEnLM4S3SqyaMEQYm
    0Gx9rwCfOA==
    -----END CERTIFICATE-----
    
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIERuWE1uqQNfUrsSsFv1UZs+EeGRLCt6CHPYpqxqlNDQoAoGCCqGSM49
    AwEHoUQDQgAEO/V6vB0tSwKL9EH0w5wUFNOs+76zlOpe9rMk1imc2dTACQRr/5Po
    p5YMYoHg4Mn2wp9BYk/ZAyUy5jpkSiJaRA==
    -----END EC PRIVATE KEY-----
    
