








apiVersion: v1
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 3.71.0
    helm.sh/chart: sensor-71.0.0
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXqgAwIBAgIUTWZDzGteHfypvw//ETMLoA6JMNkwCgYIKoZIzj0EAwIw
    SDEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYD
    VQQFExQxNzAzMDA3Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwMTEzMDBaFw0yNzA4
    MTAwMTEzMDBaMEgxJzAlBgNVBAMTHlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhv
    cml0eTEdMBsGA1UEBRMUMTcwMzAwNzM3NTgxODkxNjQ2MDQwWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAAQ5/RRzozwS+RazzqD9oVxUW7/72HKJlCVU+S787oxPoBea
    XrWyvaZwFyLvzCjr+LTJhEMFtSJmPbPMOM1KHgHAo0IwQDAOBgNVHQ8BAf8EBAMC
    AQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUWzswzWircLRrXDkvRq3df3xu
    Kt8wCgYIKoZIzj0EAwIDRwAwRAIgHXzkjgbccM8aX4uldyEMjqJyTT54ofAzaTOv
    Sr/0aJgCIGxrmaK7QQ1N5Tz3tHH5UmseVhHbMm4HSSxR10fcAMWs
    -----END CERTIFICATE-----
    
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICgzCCAimgAwIBAgIIeIKDTDtBtyMwCgYIKoZIzj0EAwIwSDEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MR0wGwYDVQQFExQxNzAzMDA3
    Mzc1ODE4OTE2NDYwNDAeFw0yMjA4MTEwMTIxMDBaFw0yMzA4MTEwMjIxMDBaMHYx
    FzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0wOwYDVQQDDDRTRU5TT1JfU0VSVklD
    RTogYzRjOGI5YzktNGRlOS00YWI3LWE5NjctYmUwZWY5MDdmZTRjMRwwGgYDVQQF
    ExM4NjgzNjQ3Mzk0OTU4NjUzMjE5MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
    BaMHLq2MkwSCOuwC2IR3HsZiKvzDVZd+/8h4bJSEbym0i0TWU7PLN1sbwv86Kdiq
    suAm4zmuuPUnyxpwpUQvs6OBzjCByzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
    FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFJq/
    ywmz9NoVw7iSyvACeL3dUZK6MB8GA1UdIwQYMBaAFFs7MM1oq3C0a1w5L0at3X98
    birfMEwGA1UdEQRFMEOCD3NlbnNvci5zdGFja3JveIITc2Vuc29yLnN0YWNrcm94
    LnN2Y4Ibc2Vuc29yLXdlYmhvb2suc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0gA
    MEUCIQDnq8wE/oTmseXEFukn0cahXcAvLvufe6130yUSfojffwIgNBe8eIsDcoqm
    vwAcBcDqsy18aDE9+l2IC09+nMyUc4E=
    -----END CERTIFICATE-----
    
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIPpqjiQG5dh7h9/ljUEYUv5VQYphVPn3T1r7s/jxZmcLoAoGCCqGSM49
    AwEHoUQDQgAEBaMHLq2MkwSCOuwC2IR3HsZiKvzDVZd+/8h4bJSEbym0i0TWU7PL
    N1sbwv86KdiqsuAm4zmuuPUnyxpwpUQvsw==
    -----END EC PRIVATE KEY-----
    
